SELECT COUNT (DISTINCT(APP)) as APPS, COUNT (DISTINCT(CATEGORY)) AS CATEGORYS
FROM [Google Database].[dbo].[googleplaystore];

SELECT CATEGORY, COUNT (DISTINCT(APP)) AS COUNT
FROM [Google Database].[dbo].[googleplaystore]
GROUP BY CATEGORY
ORDER BY COUNT DESC;

SELECT TOP(10) APP, RATING
FROM [Google Database].[dbo].[googleplaystore]
WHERE TYPE = 'Free'
ORDER BY RATING DESC;

SELECT TOP(10) APP, COUNT(REVIEWS) AS REVIEWS
FROM [Google Database].[dbo].[googleplaystore]
GROUP BY APP
ORDER BY COUNT(REVIEWS) DESC;

SELECT CATEGORY, CAST(ROUND(AVG(RATING),2) AS FLOAT) AS RATING
FROM [Google Database].[dbo].[googleplaystore]
GROUP BY CATEGORY;


SELECT CATEGORY, COUNT (INSTALLS) AS COUNT
FROM [Google Database].[dbo].[googleplaystore]
GROUP BY CATEGORY
ORDER BY COUNT DESC;

SELECT *,
CASE WHEN ISNUMERIC(SENTIMENT_POLARITY) = 1 THEN CAST(SENTIMENT_POLARITY AS FLOAT) ELSE 0.0 END AS SENTIMENT_POLARITY2,
CASE WHEN ISNUMERIC(SENTIMENT_SUBJECTIVITY) = 1 THEN CAST(ROUND(SENTIMENT_SUBJECTIVITY,2) AS FLOAT) ELSE 0.0 END AS SENTIMENT_SUBJECTIVITY2
FROM [Google Database].[dbo].[googleplaystore_user_reviews];


SELECT CATEGORY, ROUND(AVG(SENTIMENT_POLARITY2),2) AS AVERAGE
FROM [Google Database].[dbo].[googleplaystore] AS G1
INNER JOIN [master].[dbo].[REVIEWS] AS G2
ON G1.APP= G2.APP
GROUP BY CATEGORY
ORDER BY AVERAGE DESC


SELECT 
G1.CATEGORY, 
SENTIMENT,
COUNT(*) AS COUNT
FROM [Google Database].[dbo].[googleplaystore] AS G1
INNER JOIN [master].[dbo].[REVIEWS] AS G2
ON G1.APP= G2.APP
WHERE SENTIMENT <> 'nan'
GROUP BY G1.CATEGORY, SENTIMENT
ORDER BY CATEGORY


SELECT
    CATEGORY,
    SUM(CASE WHEN SENTIMENT = 'Positive' THEN 1 ELSE 0 END) AS SentimientoPositivo,
    SUM(CASE WHEN SENTIMENT = 'Negative' THEN 1 ELSE 0 END) AS SentimientoNegativo,
    SUM(CASE WHEN SENTIMENT = 'Neutral' THEN 1 ELSE 0 END) AS SentimientoNeutral
FROM
    [Google Database].[dbo].[googleplaystore] AS G1
INNER JOIN
    [master].[dbo].[REVIEWS] AS G2
ON
    G1.APP = G2.APP
GROUP BY
    CATEGORY;



